name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PEP8 check
        run: |
          python -m pycodestyle src tests

      - name: Run tests
        run: |
          mkdir -p reports
          python -m pytest tests --html=reports/report.html --self-contained-html

      - name: Upload pytest HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/report.html